name: Auto Generate Manifest

on:
  push:

permissions:
  contents: write

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate Manifest
        run: python generate_manifest.py

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add manifest.json

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Auto update manifest"
            git push
          fi
